"use client";
import AuthProtected from "@/components/AuthProtected";
import "./globals.css";
import { ThemeProvider } from "@material-tailwind/react";

export const metadata = {
  title: "AandM",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProtected >
          <ThemeProvider>{children}</ThemeProvider>
        </AuthProtected>
      </body>
    </html>
  );
}
